# Funding options for Call2Action
# Support the development of this project

# Buy Me a Coffee
custom: ['https://buymeacoffee.com/leoneperdigao']

# GitHub Sponsors (uncomment to enable)
# github: [leoneperdigao]

# Other platforms (uncomment to enable)
# patreon: leoneperdigao
# ko_fi: leoneperdigao
# open_collective: call2action
# tidelift: pypi/call2action
